import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/Navigation";
import { LoadingProvider } from "@/components/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`antialiased`}
      >
        <LoadingProvider>
          <div className="min-h-screen bg-gray-50">
            <Navigation />
            <main>
              {children}
            </main>
          </div>
        </LoadingProvider>
      </body>
    </html>
  );
}
